config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable resources in-process
  mount ActionCable.server => '/cable'

  root   'main#index'
  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'conversations/:sender_username/:recipient_username', to: 'conversations#show', as: :show_conversation
  post 'conversations/:conversation_id/messages', to: 'messages#create', as: :messages

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_reader

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email
  before_create :create_activation_digest, :downcase_username

  has_secure_password

  has_many :messages, inverse_of: :user

  validates :username, presence: true, uniqueness: true, length: { maximum: 50 },
            format: { with: /\A[a-z]+\w*\z/i }
  validates :email,
            presence: true, uniqueness: { case_sensitive: false },
            length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # will_paginate per_page settings for this model
  self.per_page = 20

  # over this method to use username to construct url
  def to_param
    username
  end

  # Returns the hash digest of the given password. For test fixture.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token. For remember me feature.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Check if User can be authenticated by token for specific attribute.
  # Returns true if the given token matches the digest.
  # e.g.
  # user.authenticated?(:remember, remember_token)
  # user.authenticated?(:password, password)
  # user.authenticated?(:activation, activation_token)
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attributes(activated: true, activated_at: Time.zone.now)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_mail
    UserMailer.account_activation(self).deliver_now
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns unread readable message count for a user.
  def unread_count
    messages = Message.for_user(id)
    count = 0
    messages.each do |m|
      if m.unread?(self)
        count += 1
      end
    end
    count
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def downcase_username
      self.username = username.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_logged_in, only: [:edit, :update, :index, :destroy]
  before_action :check_correct_user, only: [:edit, :update]
  before_action :check_admin_user, only: [:destroy]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find_by(username: params[:id])
    unless @user.activated?
      redirect_to root_url
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_mail
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
  	else
  		render :new
  	end
  end

  def edit
    @user = User.find_by(username: params[:id])
  end

  def update
    @user = User.find_by(username: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.username}'s profile updated successfully."
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    User.find_by(username: params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  private

  	def user_params
  		params.require(:user).permit(:username, :email, :password, :password_confirmation)
  	end

    # Before filters

    # Confirms the correct user.
    def check_correct_user
      @user = User.find_by(username: params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def check_admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {})
    options_default = { size: 80, class: "gravatar" }
    options.reverse_merge!(options_default)

		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{options[:size]}"
		image_tag(gravatar_url, alt: user.username, class: options[:class])
	end

  def show_unread_count
    if logged_in? && current_user.unread_count > 0
      content_tag(:div, "You have #{current_user.unread_count} unread messages.", class: "alert alert-info")
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.username, user_url(user.username) %>
  <% unless user.eql? current_user %>
    <%= link_to 'chat', show_conversation_path(sender_username: current_user.username,
                                               recipient_username: user.username) %>
  <% end %>
  <% if current_user.admin? %>
    <%= link_to 'delete', user_url(user.username), method: :delete,
                data: { confirm: "You sure to delete #{user.username}?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div class="section">
  <h1>All users</h1>

  <ul class="users">
    <%= render @users %>
  </ul>
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, "Create my account") %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
<aside class="col-md-4">
	<section class="user-info">
	<h1>
	  <%= gravatar_for @user %>
	  <%= @user.username %>
	</h1>
</section>
</aside>
</div>